# Generated by Django 4.2.7 on 2024-01-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOufitMen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='prod_Imagen',
            field=models.ImageField(upload_to='imgProductos/'),
        ),
    ]
