# Generated by Django 4.2.7 on 2024-01-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOufitMen', '0002_alter_producto_prod_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='prod_Color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_Descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_Nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_Precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_Talla',
            field=models.CharField(max_length=10),
        ),
    ]
