# Generated by Django 4.2.7 on 2024-01-20 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOufitMen', '0003_alter_producto_prod_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_producto',
            fields=[
                ('Id_Categoria', models.AutoField(primary_key=True, serialize=False, verbose_name='id categoria')),
                ('Nombre', models.TextField(max_length=40)),
                ('Descripcion', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('Pd_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Pedido')),
                ('Pd_Id_Usuario', models.BigIntegerField(verbose_name='ID del Usuario')),
                ('Pd_Fecha_envio', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Usu_Documento', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='N° Documento')),
                ('Usu_Nombre', models.TextField(max_length=40)),
                ('Usu_Apellido', models.TextField(max_length=40)),
                ('Usu_Contraseña', models.TextField(max_length=30)),
                ('Usu_Correo', models.EmailField(max_length=50, verbose_name='Correo Electronico')),
            ],
        ),
        migrations.CreateModel(
            name='Metodo_pago',
            fields=[
                ('Mp_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID  de pago')),
                ('Mp_Metodo', models.TextField(max_length=40)),
                ('Mp_Pago', models.IntegerField()),
                ('Mp_Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOufitMen.pedido', verbose_name='ID pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Envio_Producto',
            fields=[
                ('Env_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del envios')),
                ('Env_Fecha_hora', models.DateTimeField()),
                ('Env_Id_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOufitMen.producto', verbose_name='ID del Producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('Detap_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detalle pedido')),
                ('Detap_Fecha_Envio', models.DateTimeField()),
                ('Detap_Direccion', models.TextField(max_length=40)),
                ('Detap_Estado_Envio', models.TextField(max_length=50)),
                ('Deta_Id_Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOufitMen.pedido', verbose_name='ID Pedido')),
                ('Detap_Id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOufitMen.usuario', verbose_name='ID Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('Ct_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Comentario')),
                ('Ct', models.TextField(max_length=250)),
                ('Ct_Cali', models.IntegerField()),
                ('Ct_Id_Prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOufitMen.producto', verbose_name='ID Producto')),
                ('Ct_Id_Usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOufitMen.usuario', verbose_name='ID Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('Car_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID carro de compras')),
                ('Car_Estado', models.TextField(max_length=30)),
                ('Car_Id_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOufitMen.producto', verbose_name='ID Producto')),
                ('Car_Id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOufitMen.usuario', verbose_name='ID Usuario')),
            ],
        ),
    ]
