# Generated by Django 4.2.7 on 2024-02-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOufitMen', '0005_usuario_last_login_usuario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritocompra',
            name='Car_Id_Usuario',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='Ct_Id_Usu',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='Detap_Id_Usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
