# Generated by Django 4.2.7 on 2024-02-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOufitMen', '0007_usuario_carritocompra_car_id_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Password',
        ),
    ]
