# Generated by Django 4.2.7 on 2024-03-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOufitMen', '0008_remove_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Usu_Correo',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Correo Electronico'),
        ),
    ]
